version: '2'
services:
  mongodb:
    image: mongo:3.2
    container_name: eidb
    volumes:
      - /data/eiblog/mgodb:/data/db
    restart: always
  elasticsearch:
    image: elasticsearch:2.4
    container_name: eisearch
    volumes:
      - /data/eiblog/conf/es/config:/usr/share/elasticsearch/config
      - /data/eiblog/conf/es/plugins:/usr/share/elasticsearch/plugins
      - /data/eiblog/esdata/data:/usr/share/elasticsearch/data
      - /data/eiblog/esdata/logs:/usr/share/elasticsearch/logs
    environment:    
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    # 需注释掉
    ports:
      - "9200:9200"
    restart: always
  eiblog:
    image: registry.cn-hangzhou.aliyuncs.com/deepzz/eiblog
    container_name: eiblog
    volumes:
      - /data/eiblog/logdata:/eiblog/logdata
      - /data/eiblog/conf:/eiblog/conf
      - /data/eiblog/static:/eiblog/static
    links:
      - elasticsearch
      - mongodb
    ports:
      - "9000:9000"
    restart: always
